<response cycle="001" cvus="000" thread="001" suite="Critical" name="view_stuff" step="001" number="001" type="get" result="Error" url="http://localhost:3000/upcoming" code="-1" description="View the upcoming page" time="1418344364.12" duration="0.00125694274902" traceback='Traceback (most recent call last):&#10;   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/funkload/FunkLoadTestCase.py", line 202, in _connect&#10;    cert_file=self._certfile_path, method=rtype)&#10;   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/funkload/PatchWebunit.py", line 360, in WF_fetch&#10;    h.endheaders()&#10;   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders&#10;    self._send_output(message_body)&#10;   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output&#10;    self.send(msg)&#10;   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send&#10;    self.connect()&#10;   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 772, in connect&#10;    self.timeout, self.source_address)&#10;   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection&#10;    raise err&#10; error: [Errno 61] Connection refused&#10;' />
<testResult cycle="001" cvus="000" thread="001" suite="Critical" name="view_stuff"  time="1418344364.12" result="Error" steps="1" duration="0.00573301315308" connection_duration="0.00125694274902" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/Users/larsbrusletto/Documents/UCSB_classes/Xup/loadtestingsteffen/test_Critical.py&quot;, line 20, in view_stuff&#10;    self.get(server_url + &quot;/upcoming&quot;, description=&quot;View the upcoming page&quot;)&#10;   File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/funkload/FunkLoadTestCase.py&quot;, line 221, in _connect&#10;    raise SocketError(&quot;Can't load %s.&quot; % url)&#10; error: Can't load http://localhost:3000/upcoming.&#10;" />
